routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::Auth();
Route::get('/', function () {
    return view('welcome');
});
Route::get('setlocale/{locale}', 'MiscController@setlocale');
Route::middleware(['auth'])->group(function () {
		Route::resource('/admin/about_uses', 'Admin\AboutUsController', ['as' => 'admin']);
		Route::resource('/admin/about_us_translations', 'Admin\AboutUsTranslationController', ['as' => 'admin']);
		Route::resource('/admin/main_banners', 'Admin\MainBannerController', ['as' => 'admin']);
		Route::resource('/admin/event_banners', 'Admin\EventBannerController', ['as' => 'admin']);
		Route::resource('/admin/event_labels', 'Admin\EventLabelController', ['as' => 'admin']);
		Route::resource('/admin/dream_banners', 'Admin\DreamBannerController', ['as' => 'admin']);
		Route::resource('/admin/story_banners', 'Admin\StoryBannerController', ['as' => 'admin']);
		Route::resource('/admin/donation_banners', 'Admin\DonationBannerController', ['as' => 'admin']);
		Route::resource('/admin/shipping_methods', 'Admin\ShippingMethodController', ['as' => 'admin']);
		Route::resource('/admin/units', 'Admin\UnitController', ['as' => 'admin']);
		Route::resource('/admin/initiators', 'Admin\InitiatorController', ['as' => 'admin']);
		Route::resource('/admin/general_donations', 'Admin\GeneralDonationController', ['as' => 'admin']);
		Route::resource('/admin/notifications', 'Admin\NotificationController', ['as' => 'admin']);
		Route::resource('/admin/privacy_policies', 'Admin\PrivacyPolicyController', ['as' => 'admin']);
		Route::resource('/admin/privacy_policy_translations', 'Admin\PrivacyPolicyTranslationController', ['as' => 'admin']);
		Route::resource('/admin/donation_categories', 'Admin\DonationCategoryController', ['as' => 'admin']);
		Route::resource('/admin/donation_category_banners', 'Admin\DonationCategoryBannerController', ['as' => 'admin']);
		Route::resource('/admin/gallery_banners', 'Admin\GalleryBannerController', ['as' => 'admin']);
		Route::resource('/admin/contact_us_banners', 'Admin\ContactUsBannerController', ['as' => 'admin']);
		Route::resource('/admin/faq_banners', 'Admin\FaqBannerController', ['as' => 'admin']);
		Route::resource('/admin/consumer_banners', 'Admin\ConsumerBannerController', ['as' => 'admin']);
		Route::resource('/admin/consumers', 'Admin\ConsumerController', ['as' => 'admin']);
		Route::resource('/admin/stories', 'Admin\StoryController', ['as' => 'admin']);
		Route::resource('/admin/story_translations', 'Admin\StoryTranslationController', ['as' => 'admin']);
		Route::resource('/admin/story_comments', 'Admin\StoryCommentController', ['as' => 'admin']);
		Route::resource('/admin/story_donations', 'Admin\StoryDonationController', ['as' => 'admin']);
		Route::resource('/admin/events', 'Admin\EventController', ['as' => 'admin']);
		Route::resource('/admin/event_translations', 'Admin\EventTranslationController', ['as' => 'admin']);
		Route::resource('/admin/event_comments', 'Admin\EventCommentController', ['as' => 'admin']);
		Route::resource('/admin/event_donations', 'Admin\EventDonationController', ['as' => 'admin']);
		Route::resource('/admin/event_goods_donations', 'Admin\EventGoodsDonationController', ['as' => 'admin']);
		Route::resource('/admin/dreams', 'Admin\DreamController', ['as' => 'admin']);
		Route::resource('/admin/dream_translations', 'Admin\DreamTranslationController', ['as' => 'admin']);
		Route::resource('/admin/dream_comments', 'Admin\DreamCommentController', ['as' => 'admin']);
		Route::resource('/admin/dream_donations', 'Admin\DreamDonationController', ['as' => 'admin']);
		Route::resource('/admin/dream_goods_donations', 'Admin\DreamGoodsDonationController', ['as' => 'admin']);
		Route::resource('/admin/galleries', 'Admin\GalleryController', ['as' => 'admin']);
		Route::resource('/admin/gallery_translations', 'Admin\GalleryTranslationController', ['as' => 'admin']);
		Route::resource('/admin/gallery_comments', 'Admin\GalleryCommentController', ['as' => 'admin']);
		Route::resource('/admin/faqs', 'Admin\FaqController', ['as' => 'admin']);
		Route::resource('/admin/faq_translations', 'Admin\FaqTranslationController', ['as' => 'admin']);
		Route::resource('/admin/faq_categories', 'Admin\FaqCategoryController', ['as' => 'admin']);
		Route::resource('/admin/users', 'Admin\UserController', ['as' => 'admin']);
    	Route::get('/admin/permissions', 'Admin\MiscController@permissions')->name('admin.permissions.index');
    	Route::get('/admin/permissions/create', 'Admin\MiscController@permissions_create')->name('admin.permissions.create');
    	Route::post('/admin/permissions/store', 'Admin\MiscController@permissions_store')->name('admin.permissions.store');
    	Route::put('/admin/permissions/update/{id}', 'Admin\MiscController@permissions_update')->name('admin.permissions.update');
    	Route::delete('/admin/permissions/destroy/{id}', 'Admin\MiscController@permissions_destroy')->name('admin.permissions.destroy');
    	Route::get('/admin/permissions/edit/{id}', 'Admin\MiscController@permissions_edit')->name('admin.permissions.edit');
    	Route::get('/home', 'Admin\HomeController@index')->name('home');
});

app/Models/Consumer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;
use Tymon\JWTAuth\Contracts\JWTSubject;


class Consumer extends Authenticatable implements JWTSubject
{
    use SoftDeletes;
    use Notifiable;
    

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'consumers';

    

    protected $casts = [
		'profile_image' => 'string',
		'name' => 'string',
		'password' => 'string',
		'email' => 'string',
		'phone_number' => 'string',
		'birth_date' => 'datetime',
		'gender' => 'string',
		'home_address' => 'string',
		'office_address' => 'string',
		'institution_name' => 'string',
		'active_flag' => 'boolean',
		'created_by' => 'string',
		'updated_by' => 'string',
    ];

    protected $dates = [
		'birth_date',
        'created_at',
        'updated_at',
    ];
    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = [
		'profile_image',
		'name',
		'password',
		'email',
		'phone_number',
		'birth_date',
		'gender',
		'home_address',
		'office_address',
		'active_flag',
		'institution_name',
		'created_by',
		'updated_by',
	];

    
    
	public static function boot()
	{
		parent::boot();
		$class = get_called_class();
		$class::observe(new \App\Observers\CreatedUpdatedBy);
	}

    
	public function created_by_user()
	{
		return $this->belongsTo(\App\User::class, 'created_by', 'id');
	}
	public function updated_by_user()
	{
		return $this->belongsTo(\App\User::class, 'updated_by', 'id');
	}
    
	public function events()
	{
		return $this->hasMany(\App\Models\Event::class);
	}

	public function event_donations()
	{
		return $this->hasMany(\App\Models\EventDonation::class);
	}

	public function dreams()
	{
		return $this->hasMany(\App\Models\Dream::class);
	}

	public function dream_donations()
	{
		return $this->hasMany(\App\Models\DreamDonation::class);
	}

	public function stories()
	{
		return $this->hasMany(\App\Models\Story::class);
	}


	public function story_donations()
	{
		return $this->hasMany(\App\Models\StoryDonation::class);
	}



	public function event_comments()
	{
		return $this->hasMany(\App\Models\EventComment::class);
	}

	public function dream_comments()
	{
		return $this->hasMany(\App\Models\DreamComment::class);
	}

	public function story_comments()
	{
		return $this->hasMany(\App\Models\StoryComment::class);
	}

	public function gallery_comments()
	{
		return $this->hasMany(\App\Models\GalleryComment::class);
	}


    public function scopeSearch($query, $value)
    {
        return $query->where(function ($query) use ($value) {
			$query->where('profile_image', 'like', '%' . $value . '%');
			$query->orWhere('name', 'like', '%' . $value . '%');
			$query->orWhere('password', 'like', '%' . $value . '%');
			$query->orWhere('email', 'like', '%' . $value . '%');
			$query->orWhere('phone_number', 'like', '%' . $value . '%');
			$query->orWhere('birth_date', 'like', '%' . $value . '%');
			$query->orWhere('gender', 'like', '%' . $value . '%');
			$query->orWhere('home_address', 'like', '%' . $value . '%');
			$query->orWhere('office_address', 'like', '%' . $value . '%');
        });
    }

     public function getJWTIdentifier()
    {
        return $this->getKey();
    }
    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }

    public function getFullNameAttribute()
    {
    	return $this->name;
    }
}

app/Models/DreamComment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class DreamComment extends Model
{
    use SoftDeletes;
    

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'dream_comments';

    

    protected $casts = [
		'dream_id' => 'string',
		'consumer_id' => 'string',
		'comment' => 'string',
		'reply_flag' => 'boolean',
		'verification_flag' => 'boolean',
		'reply_header_id' => 'string',
		'created_by' => 'string',
		'updated_by' => 'string',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
    ];
    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = [
		'dream_id',
		'consumer_id',
		'comment',
		'reply_flag',
		'verification_flag',
		'reply_header_id',
		'created_by',
		'updated_by',
	];

    
    
	public static function boot()
	{
		parent::boot();
		$class = get_called_class();
		$class::observe(new \App\Observers\CreatedUpdatedBy);
		$class::observe(new \App\Observers\ConsumerCreatedUpdated);
	}

    
	public function created_by_user()
	{
		return $this->belongsTo(\App\User::class, 'created_by', 'id');
	}
	public function updated_by_user()
	{
		return $this->belongsTo(\App\User::class, 'updated_by', 'id');
	}
	public function header()
	{
		return $this->belongsTo(DreamComment::class, 'reply_header_id', 'id');
	}

	public function replies()
	{
		return $this->hasMany(DreamComment::class, 'reply_header_id' , 'id' );
	}
	
	public function dream()
	{
		return $this->belongsTo(Dream::class);
	}

	public function consumer()
	{
		return $this->belongsTo(Consumer::class);
	}
    

    public function scopeSearch($query, $value)
    {
        return $query->where(function ($query) use ($value) {
			$query->orWhere('comment', 'like', '%' . $value . '%');
        });
    }
}

app/Http/Controllers/Admin/DreamCommentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\DreamComment;
use App\Models\Dream;
use App\Models\Consumer;
use App\Http\Controllers\Controller;
use App\Http\Requests\DreamCommentCreateRequest;
use App\Http\Requests\DreamCommentUpdateRequest;
use Illuminate\Http\Request;

class DreamCommentController extends Controller
{
    public $dream_comments;
    public $dreams;
    public $consumers;

    public function __construct(DreamComment $dream_comments, Dream $dreams, Consumer $consumers)
    {
        $this->dream_comments = $dream_comments;
        $this->dreams = $dreams;
        $this->consumers = $consumers;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        check_permission('menu dream_comments');
        if ($request->has('search')) {
            $data = $this->dream_comments->search($request->search)->orderBy('id', 'desc')->paginate();
        } else {
            $data = $this->dream_comments->orderBy('id', 'desc')->paginate(20);

        }
        return view('admin.dream_comments.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        check_permission('create dream_comments');
        $consumers = $this->consumers->all();
        $headers = $this->dream_comments->whereNull('reply_header_id')->get();
        $dreams = $this->dreams->get();

        return view('admin.dream_comments.create', compact('consumers', "headers", "dreams"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DreamCommentCreateRequest $request)
    {
        check_permission('create dream_comments');
        $input = $request->except("_token");
        try {
            $this->dream_comments->create($input);
            flash('DreamComment Saved')->success();
            return redirect()->route('admin.dream_comments.index');
        } catch (\Exception $e) {
            flash('Error :' . $e->getMessage())->error();
            return back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        check_permission('read dream_comments');
        return view('admin.dream_comments.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        
        check_permission('update dream_comments');
        $consumers = $this->consumers->all();
        $headers = $this->dream_comments->whereNull('reply_header_id')->get();
        $dreams = $this->dreams->get();
        $data = $this->dream_comments->find($id);
        return view('admin.dream_comments.edit', compact('consumers', 'headers', 'dreams', 'data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(DreamCommentUpdateRequest $request, $id)
    {
        check_permission('update dream_comments');
        $this->dream_comments = $this->dream_comments->findOrFail($id);
        $input = $request->except(["_token", "_method"]);
        try {
            $this->dream_comments->update($input);
            flash('DreamComment Saved')->success();
            return redirect()->route('admin.dream_comments.index');
        } catch (\Exception $e) {
            flash('Error :' . $e->getMessage())->error();
            return back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        check_permission('delete dream_comments');
        try {
            $this->dream_comments->destroy($id);
            flash('DreamComment Deleted')->success();
            return redirect()->route('admin.dream_comments.index');
        } catch (\Exception $e) {
            flash('Error :' . $e->getMessage())->error();
            return back();
        }
    }
}

resources/views/admin/dream_comments/create.blade.php
@extends('adminlte::page')

@section('title', 'Create Dream Comment')

@section('content_header')
    <h1>Dream Comment</h1>
    <ol class="breadcrumb">
	    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
	    <li><a href="/admin/dream_comments">Dream Comment</a></li>
	    <li class="active">Create</li>
	 </ol>
@stop
@section('content')
		@include('admin.misc.alert')
	  <div class="row">
	  	<form class="" method="post" action="{!! route('admin.dream_comments.store') !!}" enctype="multipart/form-data">
	  		@csrf
	  		@include('admin.dream_comments.form', ["title" => "Add Dream Comment", 'edit' => false])
  		</form>
	  </div>
@stop

@section('js')

@stop

resources/views/admin/dream_comments/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit Dream Comment')

@section('content_header')
    <h1>Dream Comment</h1>
    <ol class="breadcrumb">
	    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
	    <li><a href="/admin/dream_comments">Dream Comment</a></li>
	    <li class="active">Edit</li>
	 </ol>
@stop
@section('content')
		@include('admin.misc.alert')
	  <div class="row">
	  	<form class="" method="post" action="{!! route('admin.dream_comments.update', ['id' => $data->id]) !!}" enctype="multipart/form-data">
			<input type="hidden" name="_method" value="put" />
	  		@csrf
	  		@include('admin.dream_comments.form', ["title" => "Edit Dream Comment", 'edit' => true])
  		</form>
	  </div>
@stop

@section('js')

@stop

resources/views/admin/dream_comments/form.blade.php
<div class="col-md-8 col-md-offset-2">
	<div class="box box-primary">
		<div class="box-header">
      <h3 class="box-title">
				{!! $title !!}
      </h3>
    </div>
		<div class="box-body">
				<div class='form-group'>
						<label for=''>Dream</label>
						<select name='dream_id'  class='form-control'>
							<option value='' >Select First</option>
							@foreach($dreams as $dream)	
								<option value='{!! $dream->id !!}' {!! $edit ? $dream->id == $data->dream_id ? 'SELECTED' : null : null !!}>{!! $dream->title !!}</option>
							@endforeach
						</select>
				</div>
				<div class='form-group'>
						<label for=''>Consumer</label>
							<select name='consumer_id'  class='form-control'>
							<option value='' >Select First</option>
							@foreach($consumers as $consumer)	
								<option value='{!! $consumer->id !!}' {!! $edit ? $consumer->id == $data->consumer_id ? 'SELECTED' : null : null !!}>{!! $consumer->name !!}</option>
							@endforeach
						</select>
				</div>
				<div class='form-group'>
						<label for=''>Comment</label>
						<textarea name='comment'  class='form-control' rows='5'>{!! $edit ? $data->comment : null !!}</textarea>
				</div>
				<div class='form-group'>
						<label for=''>Reply Flag</label>
						<input name='reply_flag' type='radio' value='0' {!! $edit ? $data->reply_flag == '0' ? 'CHECKED' : null : null !!} /> No
						<input name='reply_flag' type='radio' value='1' {!! $edit ? $data->reply_flag == '1' ? 'CHECKED' : null : null !!} /> Yes
				</div>
				<div class='form-group'>
						<label for=''>Verification Flag</label>
						<select name="verification_flag" class="form-control">
							<option value="0" {!! $edit ? $data->verification_flag == '0' ? 'SELECTED' : null : null !!}>Unverified</option>
							<option value="1" {!! $edit ? $data->verification_flag == '1' ? 'SELECTED' : null : null !!}>Verified</option>
						</select>
				</div>
				<div class='form-group'>
						<label for=''>Reply Header</label>
						
						<select name='reply_header_id'  class='form-control'>
							<option value='' >Select First</option>
							@foreach($headers as $header)	
								<option value='{!! $header->id !!}' {!! $edit ? $header->id == $data->reply_header_id ? 'SELECTED' : null : null !!}>{!! $header->comment !!}</option>
							@endforeach
						</select>
				</div>
			<button type="submit" class="btn btn-success">Submit</button>
    </div>
  </div>
</div>

resources/views/admin/dream_comments/index.blade.php
@extends('adminlte::page')

@section('title', 'Dream Comment')

@section('content_header')
    <h1>Dream Comment</h1>
    <ol class="breadcrumb">
	    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
	    <li><a href="/admin/dream_comments">Dream Comment</a></li>
	    <li class="active">Lists</li>
	 </ol>
@stop


@section('content')
    @include('admin.misc.alert')
    <div class="row">
    	<div class="col-md-12">
    		<div class="box box-primary">
					<div class="box-header">
            <h3 class="box-title">
            @if(env('FULL_ACCESS'))
              <a href="{!! route('admin.dream_comments.create') !!}" class="btn btn-primary pull-left"><i class="fa fa-plus"></i> Dream Comment</a>

			@endif
            	

            </h3>
            <div class="box-tools">

                <form>
              <div class="input-group input-group-sm" style="width: 300px;">
                <input type="text" name="search" class="form-control pull-right" placeholder="Search">

                <div class="input-group-btn">
                  <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                </div>
              </div>
                </form>
            </div>
          </div>
          <div class="box-body table-responsive">
          	<table class="table table-hover">
						  <tbody><tr>
						    <th>#</th>
								<th>Dream</th>
								<th>Consumer</th>
								<th>Comment</th>
								<th>Reply Flag</th>
								<th>Verification Flag</th>
								<th>Reply Header</th>
								<th>Created</th>
								<th>Updated</th>
						    <th></th>
						  </tr>
						    @foreach($data as $i => $d)
						    <tr>
						      <td>{!! $i + $data->firstItem() !!}</td>
									<td>{!! optional($d->dream)->title !!}</td>
									<td>{!! optional($d->consumer)->full_name !!}</td>
									<td>{!! $d->comment !!}</td>
									<td>{!! $d->reply_flag ? '<span class=\'glyphicon glyphicon-ok-sign text-success\'></span>' : '<span class=\'glyphicon glyphicon-remove-sign text-danger\'></span>' !!}</td>
									<td>{!! $d->verification_flag ? '<span class=\'glyphicon glyphicon-ok-sign text-success\'></span>' : '<span class=\'glyphicon glyphicon-remove-sign text-danger\'></span>' !!}</td>
									<td>{!! optional($d->header)->comment !!}</td>
									<td>{!! optional($d->created_by_user)->name !!}</td>
									<td>{!! optional($d->updated_by_user)->name !!}</td>
						      <td>
						        <form method="post" action="{!! route('admin.dream_comments.destroy', ['id' => $d->id]) !!}">
						          <input type="hidden" name="_method" value="delete" />
						          @csrf
						        <div class="btn-group pull-right"><a href="{!! route('admin.dream_comments.edit', ['id' => $d->id]) !!}" class="btn btn-default btn-sm"><i class="fa fa-pencil"></i></a><button class="btn btn-danger btn-sm btn-delete"><i class="fa fa-trash"></i></button></div>
						        </form>
						      </td>
						    </tr>
						    @endforeach
						  </tbody>
						</table>
						{!! $data->render() !!}
          </div>
    		</div>
    	</div>

    </div>
@stop