routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::Auth();
Route::get('/', function () {
    return view('welcome');
});
Route::get('setlocale/{locale}', 'MiscController@setlocale');
Route::middleware(['auth'])->group(function () {
		Route::resource('/admin/about_uses', 'Admin\AboutUsController', ['as' => 'admin']);
		Route::resource('/admin/about_us_translations', 'Admin\AboutUsTranslationController', ['as' => 'admin']);
		Route::resource('/admin/main_banners', 'Admin\MainBannerController', ['as' => 'admin']);
		Route::resource('/admin/event_banners', 'Admin\EventBannerController', ['as' => 'admin']);
		Route::resource('/admin/event_labels', 'Admin\EventLabelController', ['as' => 'admin']);
		Route::resource('/admin/dream_banners', 'Admin\DreamBannerController', ['as' => 'admin']);
		Route::resource('/admin/story_banners', 'Admin\StoryBannerController', ['as' => 'admin']);
		Route::resource('/admin/donation_banners', 'Admin\DonationBannerController', ['as' => 'admin']);
		Route::resource('/admin/shipping_methods', 'Admin\ShippingMethodController', ['as' => 'admin']);
		Route::resource('/admin/units', 'Admin\UnitController', ['as' => 'admin']);
		Route::resource('/admin/initiators', 'Admin\InitiatorController', ['as' => 'admin']);
		Route::resource('/admin/general_donations', 'Admin\GeneralDonationController', ['as' => 'admin']);
		Route::resource('/admin/notifications', 'Admin\NotificationController', ['as' => 'admin']);
		Route::resource('/admin/privacy_policies', 'Admin\PrivacyPolicyController', ['as' => 'admin']);
		Route::resource('/admin/privacy_policy_translations', 'Admin\PrivacyPolicyTranslationController', ['as' => 'admin']);
		Route::resource('/admin/donation_categories', 'Admin\DonationCategoryController', ['as' => 'admin']);
		Route::resource('/admin/donation_category_banners', 'Admin\DonationCategoryBannerController', ['as' => 'admin']);
		Route::resource('/admin/gallery_banners', 'Admin\GalleryBannerController', ['as' => 'admin']);
		Route::resource('/admin/contact_us_banners', 'Admin\ContactUsBannerController', ['as' => 'admin']);
		Route::resource('/admin/faq_banners', 'Admin\FaqBannerController', ['as' => 'admin']);
		Route::resource('/admin/consumer_banners', 'Admin\ConsumerBannerController', ['as' => 'admin']);
		Route::resource('/admin/consumers', 'Admin\ConsumerController', ['as' => 'admin']);
		Route::resource('/admin/stories', 'Admin\StoryController', ['as' => 'admin']);
		Route::resource('/admin/story_translations', 'Admin\StoryTranslationController', ['as' => 'admin']);
		Route::resource('/admin/story_comments', 'Admin\StoryCommentController', ['as' => 'admin']);
		Route::resource('/admin/story_donations', 'Admin\StoryDonationController', ['as' => 'admin']);
		Route::resource('/admin/events', 'Admin\EventController', ['as' => 'admin']);
		Route::resource('/admin/event_translations', 'Admin\EventTranslationController', ['as' => 'admin']);
		Route::resource('/admin/event_comments', 'Admin\EventCommentController', ['as' => 'admin']);
		Route::resource('/admin/event_donations', 'Admin\EventDonationController', ['as' => 'admin']);
		Route::resource('/admin/event_goods_donations', 'Admin\EventGoodsDonationController', ['as' => 'admin']);
		Route::resource('/admin/dreams', 'Admin\DreamController', ['as' => 'admin']);
		Route::resource('/admin/dream_translations', 'Admin\DreamTranslationController', ['as' => 'admin']);
		Route::resource('/admin/dream_comments', 'Admin\DreamCommentController', ['as' => 'admin']);
		Route::resource('/admin/dream_donations', 'Admin\DreamDonationController', ['as' => 'admin']);
		Route::resource('/admin/dream_goods_donations', 'Admin\DreamGoodsDonationController', ['as' => 'admin']);
		Route::resource('/admin/galleries', 'Admin\GalleryController', ['as' => 'admin']);
		Route::resource('/admin/gallery_translations', 'Admin\GalleryTranslationController', ['as' => 'admin']);
		Route::resource('/admin/gallery_comments', 'Admin\GalleryCommentController', ['as' => 'admin']);
		Route::resource('/admin/faqs', 'Admin\FaqController', ['as' => 'admin']);
		Route::resource('/admin/faq_translations', 'Admin\FaqTranslationController', ['as' => 'admin']);
		Route::resource('/admin/faq_categories', 'Admin\FaqCategoryController', ['as' => 'admin']);
		Route::resource('/admin/users', 'Admin\UserController', ['as' => 'admin']);
    	Route::get('/admin/permissions', 'Admin\MiscController@permissions')->name('admin.permissions.index');
    	Route::get('/admin/permissions/create', 'Admin\MiscController@permissions_create')->name('admin.permissions.create');
    	Route::post('/admin/permissions/store', 'Admin\MiscController@permissions_store')->name('admin.permissions.store');
    	Route::put('/admin/permissions/update/{id}', 'Admin\MiscController@permissions_update')->name('admin.permissions.update');
    	Route::delete('/admin/permissions/destroy/{id}', 'Admin\MiscController@permissions_destroy')->name('admin.permissions.destroy');
    	Route::get('/admin/permissions/edit/{id}', 'Admin\MiscController@permissions_edit')->name('admin.permissions.edit');
    	Route::get('/home', 'Admin\HomeController@index')->name('home');
});

app/Models/StoryBanner.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class StoryBanner extends Model
{
    use SoftDeletes;
    

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'story_banners';

    

    protected $casts = [
		'banner' => 'string',
		'active_flag' => 'boolean',
		'created_by' => 'string',
		'updated_by' => 'string',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
    ];
    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = [
		'banner',
		'active_flag',
		'created_by',
		'updated_by',
	];

    
    
	public static function boot()
	{
		parent::boot();
		$class = get_called_class();
		$class::observe(new \App\Observers\CreatedUpdatedBy);
	}

    
	public function created_by_user()
	{
		return $this->belongsTo(\App\User::class, 'created_by', 'id');
	}
	public function updated_by_user()
	{
		return $this->belongsTo(\App\User::class, 'updated_by', 'id');
	}
    

    public function scopeSearch($query, $value)
    {
        return $query->where(function ($query) use ($value) {
			$query->where('banner', 'like', '%' . $value . '%');
        });
    }
}

app/Http/Controllers/Admin/StoryBannerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\StoryBanner;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoryBannerCreateRequest;
use App\Http\Requests\StoryBannerUpdateRequest;
use Illuminate\Http\Request;

class StoryBannerController extends Controller
{
    public $story_banners;

    public function __construct(StoryBanner $story_banners)
    {
        $this->story_banners = $story_banners;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        check_permission('menu story_banners');
        if ($request->has('search')) {
            $data = $this->story_banners->search($request->search)->orderBy('id', 'desc')->paginate();
        } else {
            $data = $this->story_banners->orderBy('id', 'desc')->paginate(20);

        }
        return view('admin.story_banners.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        check_permission('create story_banners');
        $story_banners = $this->story_banners->all();
        $data = $this->story_banners;

        return view('admin.story_banners.create', compact('data', "story_banners"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoryBannerCreateRequest $request)
    {
        check_permission('create story_banners');
        disable_active_flag($this->story_banners);
        $input = $request->except("_token");
        try {
			if($request->hasFile('banner')) {
			$path = $request->banner->store('images/story', env('FILESYSTEM_DRIVER', 'public'));
			$input['banner'] = $path;
			}
            $this->story_banners->create($input);
            flash('StoryBanner Saved')->success();
            return redirect()->route('admin.story_banners.index');
        } catch (\Exception $e) {
            flash('Error :' . $e->getMessage())->error();
            return back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        check_permission('read story_banners');
        return view('admin.story_banners.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        check_permission('update story_banners');
        $story_banners = $this->story_banners->all();
        $data = $this->story_banners->find($id);
        return view('admin.story_banners.edit', compact('data', 'story_banners'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoryBannerUpdateRequest $request, $id)
    {
        check_permission('update story_banners');
        disable_active_flag($this->story_banners);
        
        $this->story_banners = $this->story_banners->findOrFail($id);
        $input = $request->except(["_token", "_method"]);
        try {
			if($request->hasFile('banner')) {
			$path = $request->banner->store('images/story', env('FILESYSTEM_DRIVER', 'public'));
			$input['banner'] = $path;
			}
            $this->story_banners->update($input);
            flash('StoryBanner Saved')->success();
            return redirect()->route('admin.story_banners.index');
        } catch (\Exception $e) {
            flash('Error :' . $e->getMessage())->error();
            return back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        check_permission('delete story_banners');
        try {
            $this->story_banners->destroy($id);
            flash('StoryBanner Deleted')->success();
            return redirect()->route('admin.story_banners.index');
        } catch (\Exception $e) {
            flash('Error :' . $e->getMessage())->error();
            return back();
        }
    }
}

app/Http/Controllers/Api/StoryBannerController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\StoryBanner;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoryBannerApiCreateRequest;
use App\Http\Requests\StoryBannerApiUpdateRequest;
use Illuminate\Http\Request;
use App\Http\Resources\StoryBanner as StoryBannerSingle;
use App\Http\Resources\StoryBannerCollection;

class StoryBannerController extends Controller
{
    public $story_banners;

    public function __construct(StoryBanner $story_banners)
    {
        $this->story_banners = $story_banners;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    /**
     * @OA\GET(path="/api/v1/story_banners",
     *   tags={"Banner"},
     *   summary="Get Story Banners",
     *   description="Get Story Banners",
     *   @OA\Response(
     *     @OA\MediaType(mediaType="application/json"),
     *     response=200,
     *     description="successful operation",
     *     @OA\Schema(type="string"),
     *   ),
     *   @OA\Response(response=400, description="Error"),
     * )
     */
    public function index(Request $request)
    {
        return new StoryBannerSingle($this->story_banners->where('active_flag', true)->orderBy('created_at', 'desc')->firstOrFail());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        abort(404);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoryBannerApiCreateRequest $request)
    {
        abort(404);
        // try {
        //     $this->story_banners->create($request->all());
        //     return response_success('operation success');
        // } catch (\Exception $e) {
        //     return response_error('operation failed', 400);
        // }
 
    public function show($id)
    {
        abort(404);
        // return new StoryBannerSingle($this->story_banners->findOrFail($id));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        abort(404);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoryBannerApiUpdateRequest $request, $id)
    {
        $this->story_banners = $this->story_banners->findOrFail($id);
        try {
            $this->story_banners->update($request->all());
            return response_success('operation success');
        } catch (\Exception $e) {
            return response_error('operation failed', 400);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $this->story_banners->destroy($id);
            return response_success('operation success');
        } catch (\Exception $e) {
            return response_error('operation failed', 400);
        }
    }
}

resources/views/admin/story_banners/create.blade.php
@extends('adminlte::page')

@section('title', 'Create Story Banner')

@section('content_header')
    <h1>Story Banner</h1>
    <ol class="breadcrumb">
	    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
	    <li><a href="/admin/story_banners">Story Banner</a></li>
	    <li class="active">Create</li>
	 </ol>
@stop
@section('content')
		@include('admin.misc.alert')
	  <div class="row">
	  	<form class="" method="post" action="{!! route('admin.story_banners.store') !!}" enctype="multipart/form-data">
	  		@csrf
	  		@include('admin.story_banners.form', ["title" => "Add Story Banner", 'edit' => false])
  		</form>
	  </div>
@stop

@section('js')

@stop

resources/views/admin/story_banners/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit Story Banner')

@section('content_header')
    <h1>Story Banner</h1>
    <ol class="breadcrumb">
	    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
	    <li><a href="/admin/story_banners">Story Banner</a></li>
	    <li class="active">Edit</li>
	 </ol>
@stop
@section('content')
		@include('admin.misc.alert')
	  <div class="row">
	  	<form class="" method="post" action="{!! route('admin.story_banners.update', ['id' => $data->id]) !!}" enctype="multipart/form-data">
			<input type="hidden" name="_method" value="put" />
	  		@csrf
	  		@include('admin.story_banners.form', ["title" => "Edit Story Banner", 'edit' => true])
  		</form>
	  </div>
@stop

@section('js')

@stop

resources/views/admin/story_banners/form.blade.php
<div class="col-md-8 col-md-offset-2">
	<div class="box box-primary">
		<div class="box-header">
      <h3 class="box-title">
				{!! $title !!}
      </h3>
    </div>
		<div class="box-body">
				<div class='form-group'>
						<label for=''>Banner</label>
					    <input name='banner' type='file' onchange="return readURL(this, '#banner-preview')" />
						<input name='banner' type='hidden' class='form-control' value='{!! $edit ? $data->banner : null !!}' />
						@if($edit)
						<br><label>Preview</label><br>
						<img id="banner-preview" src='{!! $edit ? Storage::url($data->banner) : "/images/notfound.jpeg" !!}' width='300' onerror="this.src='/images/notfound.jpeg';" />
						@endif
				</div>
				<div class='form-group'>
						<label for=''>Active Flag</label>
						<select name="active_flag" class="form-control">
							<option value="0" {!! $edit ? $data->active_flag == '0' ? 'SELECTED' : null : null !!}>Inactive</option>
							<option value="1" {!! $edit ? $data->active_flag == '1' ? 'SELECTED' : null : null !!}>Active</option>
						</select>
				</div>
			<button type="submit" class="btn btn-success">Submit</button>
    </div>
  </div>
</div>

resources/views/admin/story_banners/index.blade.php
@extends('adminlte::page')

@section('title', 'Story Banner')

@section('content_header')
    <h1>Story Banner</h1>
    <ol class="breadcrumb">
	    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
	    <li><a href="/admin/story_banners">Story Banner</a></li>
	    <li class="active">Lists</li>
	 </ol>
@stop


@section('content')
    @include('admin.misc.alert')
    <div class="row">
    	<div class="col-md-12">
    		<div class="box box-primary">
					<div class="box-header">
            <h3 class="box-title">
              <a href="{!! route('admin.story_banners.create') !!}" class="btn btn-primary pull-left"><i class="fa fa-plus"></i> Story Banner</a>

            </h3>
            <div class="box-tools">

                <form>
              <div class="input-group input-group-sm" style="width: 300px;">
                <input type="text" name="search" class="form-control pull-right" placeholder="Search">

                <div class="input-group-btn">
                  <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                </div>
              </div>
                </form>
            </div>
          </div>
          <div class="box-body table-responsive">
          	<table class="table table-hover">
						  <tbody><tr>
						    <th>#</th>
								<th>Banner</th>
								<th>Active Flag</th>
								<th>Created</th>
								<th>Updated</th>
						    <th></th>
						  </tr>
						    @foreach($data as $i => $d)
						    <tr>
						      <td>{!! $i + $data->firstItem() !!}</td>
									<td><img src='{!! Storage::url($d->banner) !!}' width='150' onerror="this.src='/images/notfound.jpeg';" /></td>
									<td>{!! $d->active_flag ? '<span class=\'glyphicon glyphicon-ok-sign text-success\'></span>' : '<span class=\'glyphicon glyphicon-remove-sign text-danger\'></span>' !!}</td>
									<td>{!! optional($d->created_by_user)->name !!}</td>
									<td>{!! optional($d->updated_by_user)->name !!}</td>
						      <td>
						        <form method="post" action="{!! route('admin.story_banners.destroy', ['id' => $d->id]) !!}">
						          <input type="hidden" name="_method" value="delete" />
						          @csrf
						        <div class="btn-group pull-right"><a href="{!! route('admin.story_banners.edit', ['id' => $d->id]) !!}" class="btn btn-default btn-sm"><i class="fa fa-pencil"></i></a><button class="btn btn-danger btn-sm btn-delete"><i class="fa fa-trash"></i></button></div>
						        </form>
						      </td>
						    </tr>
						    @endforeach
						  </tbody>
						</table>
						{!! $data->render() !!}
          </div>
    		</div>
    	</div>

    </div>
@stop